# Generated by Django 5.0.6 on 2024-07-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('AliNom', models.CharField(db_column='AliNom', max_length=30)),
                ('AliCos', models.FloatField(blank=True, db_column='AliCos', null=True)),
                ('AliInfAña', models.TextField(blank=True, db_column='AliInfAña', null=True)),
                ('AliEstReg', models.CharField(blank=True, db_column='AliEstReg', max_length=1, null=True)),
                ('AliCod', models.CharField(db_column='AliCod', max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('DieCod', models.CharField(db_column='DieCod', max_length=10, primary_key=True, serialize=False)),
                ('DieFin', models.CharField(blank=True, db_column='DieFin', max_length=60, null=True)),
                ('DieOtrDat', models.TextField(blank=True, db_column='DieOtrDat', null=True)),
                ('DieEstReg', models.CharField(blank=True, db_column='DieEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'dieta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlimentoTipo',
            fields=[
                ('AliTipCod', models.CharField(db_column='AliTipCod', max_length=2, primary_key=True, serialize=False)),
                ('AliTipDes', models.CharField(blank=True, db_column='AliTipDes', max_length=20, null=True)),
                ('AliEstReg', models.CharField(blank=True, db_column='AliEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'alimento tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('AlmCod', models.CharField(db_column='AlmCod', max_length=10, primary_key=True, serialize=False)),
                ('AlmNot', models.TextField(blank=True, db_column='AlmNot', null=True)),
                ('AlmEstReg', models.CharField(blank=True, db_column='AlmEstReg', max_length=1, null=True)),
                ('GraAlmCapMax', models.IntegerField(db_column='GraAlmCapMax')),
                ('AlmCapMin', models.IntegerField(db_column='AlmCapMin')),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('AniCod', models.CharField(db_column='AniCod', max_length=10, primary_key=True, serialize=False)),
                ('AniPes', models.IntegerField(blank=True, db_column='AniPes', null=True)),
                ('AniAñoNac', models.IntegerField(blank=True, db_column='AniAñoNac', null=True)),
                ('AniPro', models.CharField(blank=True, db_column='AniPro', max_length=10, null=True)),
                ('AniDesDie', models.TextField(blank=True, db_column='AniDesDie', null=True)),
                ('AniEstReg', models.CharField(blank=True, db_column='AniEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalTipo',
            fields=[
                ('AniTipCod', models.CharField(db_column='AniTipCod', max_length=2, primary_key=True, serialize=False)),
                ('AniUtiDes', models.CharField(blank=True, db_column='AniUtiDes', max_length=20, null=True)),
                ('aniutieAniUtiEstRegstreg', models.CharField(blank=True, db_column='AniUtiEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'animal tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalUtilidad',
            fields=[
                ('AniUtiCod', models.CharField(db_column='AniUtiCod', max_length=1, primary_key=True, serialize=False)),
                ('AniUtiDes', models.CharField(blank=True, db_column='AniUtiDes', max_length=20, null=True)),
                ('AniUtiEstReg', models.CharField(blank=True, db_column='AniUtiEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'animal utilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CabeceraPedido',
            fields=[
                ('CabPedCod', models.IntegerField(db_column='CabPedCod', primary_key=True, serialize=False)),
                ('CabPedEstReg', models.CharField(blank=True, db_column='CabPedEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'cabecera pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('CiuCod', models.CharField(db_column='CiuCod', max_length=2, primary_key=True, serialize=False)),
                ('CiuDes', models.CharField(blank=True, db_column='CiuDes', max_length=20, null=True)),
                ('CiuEstReg', models.CharField(blank=True, db_column='CiuEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FechaInicio',
            fields=[
                ('FecIniCod', models.IntegerField(db_column='FecIniCod', primary_key=True, serialize=False)),
                ('FecIniDia', models.IntegerField(blank=True, db_column='FecIniDia', null=True)),
                ('FecIniMes', models.IntegerField(blank=True, db_column='FecIniMes', null=True)),
                ('FecIniAño', models.IntegerField(blank=True, db_column='FecIniAño', null=True)),
                ('FecIniEstReg', models.CharField(blank=True, db_column='FecIniEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'fecha inicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('EmpCod', models.IntegerField(db_column='EmpCod', primary_key=True, serialize=False)),
                ('EmpNom', models.CharField(blank=True, db_column='EmpNom', max_length=60, null=True)),
                ('DetPetCod', models.CharField(blank=True, db_column='DetPetCod', max_length=1, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('EstCod', models.CharField(db_column='EstCod', max_length=1, primary_key=True, serialize=False)),
                ('EstDes', models.CharField(blank=True, db_column='EstDes', max_length=20, null=True)),
                ('EstEstReg', models.CharField(blank=True, db_column='EstEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('GraCod', models.CharField(db_column='GraCod', max_length=10, primary_key=True, serialize=False)),
                ('GraNom', models.CharField(blank=True, db_column='GraNom', max_length=60, null=True)),
                ('GraNot', models.TextField(blank=True, db_column='GraNot', null=True)),
                ('GraEstReg', models.CharField(blank=True, db_column='GraEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'granja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magnitud',
            fields=[
                ('MagCod', models.CharField(db_column='MagCod', max_length=2, primary_key=True, serialize=False)),
                ('MagDes', models.CharField(blank=True, db_column='MagDes', max_length=20, null=True)),
                ('MagEstReg', models.CharField(blank=True, db_column='MagEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'magnitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutriente',
            fields=[
                ('NutNom', models.CharField(db_column='NutNom', max_length=10)),
                ('NutInfRel', models.TextField(blank=True, db_column='NutInfRel', null=True)),
                ('NutEstReg', models.CharField(blank=True, db_column='NutEstReg', max_length=1, null=True)),
                ('NutCod', models.CharField(db_column='NutCod', max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nutriente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('PaiCod', models.IntegerField(db_column='PaiCod', primary_key=True, serialize=False)),
                ('PaiDes', models.CharField(blank=True, db_column='PaiDes', max_length=20, null=True)),
                ('PaiEstReg', models.CharField(blank=True, db_column='PaiEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('ProCod', models.CharField(db_column='ProCod', max_length=10, primary_key=True, serialize=False)),
                ('ProNom', models.CharField(blank=True, db_column='ProNom', max_length=30, null=True)),
                ('ProCon', models.CharField(blank=True, db_column='ProCon', max_length=9, null=True)),
                ('ProInfFis', models.CharField(db_column='ProInfFis', max_length=8, unique=True)),
                ('ProDes', models.TextField(blank=True, db_column='ProDes', null=True)),
                ('ProEstReg', models.CharField(blank=True, db_column='ProEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('TomCod', models.IntegerField(db_column='TomCod', primary_key=True, serialize=False)),
                ('TomNom', models.CharField(blank=True, db_column='TomNom', max_length=20, null=True)),
                ('TomHorIni', models.TimeField(blank=True, db_column='TomHorIni', null=True)),
                ('TomHorFin', models.TimeField(blank=True, db_column='TomHorFin', null=True)),
                ('TomOtrDat', models.TextField(blank=True, db_column='TomOtrDat', null=True)),
                ('TomEstReg', models.CharField(blank=True, db_column='TomEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'toma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NutrienteAlimento',
            fields=[
                ('NutAliCanCon', models.IntegerField(blank=True, db_column='NutAliCanCon', null=True)),
                ('NutAliEstReg', models.CharField(blank=True, db_column='NutAliEstReg', max_length=1, null=True)),
                ('AliCod', models.OneToOneField(db_column='AliCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Administrador.alimento')),
            ],
            options={
                'db_table': 'nutriente alimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlimentoDietaToma',
            fields=[
                ('DieCod', models.OneToOneField(db_column='DieCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Administrador.dieta')),
                ('AliDieTomCan', models.DecimalField(blank=True, db_column='AliDieTomCan', decimal_places=2, max_digits=4, null=True)),
                ('AliDieTomEstReg', models.CharField(blank=True, db_column='AliDieTomEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'alimento dieta toma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('AlmCod', models.OneToOneField(db_column='AlmCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Administrador.almacen')),
                ('StoEst', models.CharField(blank=True, db_column='StoEst', max_length=1, null=True)),
                ('StoCanDis', models.IntegerField(blank=True, db_column='StoCanDis', null=True)),
                ('StoEstReg', models.CharField(blank=True, db_column='StoEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalNutriente',
            fields=[
                ('AniCod', models.OneToOneField(db_column='AniCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Administrador.animal')),
                ('AniNutCanNes', models.IntegerField(blank=True, db_column='AniNutCanNes', null=True)),
                ('AniNutEstReg', models.CharField(blank=True, db_column='AniNutEstReg', max_length=1, null=True)),
            ],
            options={
                'db_table': 'animal nutriente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesDePedido',
            fields=[
                ('DetPedHorLle', models.TimeField(blank=True, db_column='DetPedHorLle', null=True)),
                ('DetPedDiaLle', models.IntegerField(blank=True, db_column='DetPedDiaLle', null=True)),
                ('DetPedMesLle', models.IntegerField(blank=True, db_column='DetPedMesLle', null=True)),
                ('DetPedAñoLle', models.IntegerField(blank=True, db_column='DetPedAñoLle', null=True)),
                ('DetPedDes', models.TextField(blank=True, db_column='DetPedDes', null=True)),
                ('DetPedEstReg', models.CharField(blank=True, db_column='DetPedEstReg', max_length=1, null=True)),
                ('CabPedCod', models.OneToOneField(db_column='CabPedCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Administrador.cabecerapedido')),
            ],
            options={
                'db_table': 'detalles de pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DietaAnimalFechaInicio',
            fields=[
                ('DieAniFecDesRel', models.TextField(blank=True, db_column='DieAniFecDesRel', null=True)),
                ('DieAniFecEstReg', models.CharField(blank=True, db_column='DieAniFecEstReg', max_length=1, null=True)),
                ('FecIniCod', models.OneToOneField(db_column='FecIniCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Administrador.fechainicio')),
            ],
            options={
                'db_table': 'dieta animal fecha inicio',
                'managed': False,
            },
        ),
    ]
