# Generated by Django 5.0.6 on 2024-07-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alimentodietatoma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alimentotipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='almacen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animalnutriente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animaltipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animalutilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cabecerapedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallesdepedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dieta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dietaanimalfechainicio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fechainicio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='granja',
            options={},
        ),
        migrations.AlterModelOptions(
            name='magnitud',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nutriente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nutrientealimento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='toma',
            options={},
        ),
    ]
