# Generated by Django 5.0.6 on 2024-07-05 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_alter_alimento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='AliTipCod',
            field=models.ForeignKey(blank=True, db_column='AliTipCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.alimentotipo'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='MagCod',
            field=models.ForeignKey(blank=True, db_column='MagCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.magnitud'),
        ),
        migrations.AddField(
            model_name='alimentodietatoma',
            name='AliCod',
            field=models.ForeignKey(db_column='AliCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.alimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentodietatoma',
            name='TomCod',
            field=models.ForeignKey(db_column='TomCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.toma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='EmpCod',
            field=models.ForeignKey(db_column='EmpCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='almacen_empcod_set', to='Administrador.granja', to_field='EmpCod', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='GraCod',
            field=models.ForeignKey(db_column='GraCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.granja', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='AniTipCod',
            field=models.ForeignKey(blank=True, db_column='AniTipCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.animaltipo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='AniUtiCod',
            field=models.ForeignKey(blank=True, db_column='AniUtiCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.animalutilidad'),
        ),
        migrations.AddField(
            model_name='animalnutriente',
            name='NutCod',
            field=models.ForeignKey(db_column='NutCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.nutriente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='AlmCod',
            field=models.ForeignKey(db_column='AlmCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='EmpCod',
            field=models.ForeignKey(db_column='EmpCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cabecerapedido_empcod_set', to='Administrador.almacen', to_field='EmpCod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='GraCod',
            field=models.ForeignKey(db_column='GraCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cabecerapedido_gracod_set', to='Administrador.almacen', to_field='GraCod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='ProCod',
            field=models.ForeignKey(db_column='ProCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.proveedores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudad',
            name='PaiCod',
            field=models.ForeignKey(db_column='PaiCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.pais', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesdepedido',
            name='AliCod',
            field=models.ForeignKey(db_column='AliCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.alimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaanimalfechainicio',
            name='AniCod',
            field=models.ForeignKey(db_column='AniCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietaanimalfechainicio',
            name='DieCod',
            field=models.ForeignKey(db_column='DieCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.dieta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='CiuCod',
            field=models.ForeignKey(blank=True, db_column='CiuCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='PaiCod',
            field=models.ForeignKey(db_column='PaiCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresa_paicod_set', to='Administrador.ciudad', to_field='PaiCod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='granja',
            name='CiuCod',
            field=models.ForeignKey(blank=True, db_column='CiuCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.ciudad'),
        ),
        migrations.AddField(
            model_name='granja',
            name='EmpCod',
            field=models.ForeignKey(db_column='EmpCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.empresa', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='granja',
            name='PaiCod',
            field=models.ForeignKey(blank=True, db_column='PaiCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='granja_paicod_set', to='Administrador.ciudad', to_field='PaiCod'),
        ),
        migrations.AddField(
            model_name='nutriente',
            name='EstCod',
            field=models.ForeignKey(db_column='EstCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutriente',
            name='MagCod',
            field=models.ForeignKey(blank=True, db_column='MagCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.magnitud'),
        ),
        migrations.AddField(
            model_name='nutrientealimento',
            name='NutCod',
            field=models.ForeignKey(db_column='NutCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.nutriente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='CiuCod',
            field=models.ForeignKey(blank=True, db_column='CiuCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.ciudad'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='PaiCod',
            field=models.ForeignKey(blank=True, db_column='PaiCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores_paicod_set', to='Administrador.ciudad', to_field='PaiCod'),
        ),
        migrations.AddField(
            model_name='stock',
            name='AliCod',
            field=models.ForeignKey(db_column='AliCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.alimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='EmpCod',
            field=models.ForeignKey(db_column='EmpCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_empcod_set', to='Administrador.almacen', to_field='EmpCod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='GraCod',
            field=models.ForeignKey(db_column='GraCod', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_gracod_set', to='Administrador.almacen', to_field='GraCod'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='alimentodietatoma',
            unique_together={('DieCod', 'TomCod', 'AliCod')},
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('AlmCod', 'GraCod', 'EmpCod')},
        ),
        migrations.AlterUniqueTogether(
            name='animalnutriente',
            unique_together={('AniCod', 'NutCod')},
        ),
        migrations.AlterUniqueTogether(
            name='detallesdepedido',
            unique_together={('CabPedCod', 'AliCod')},
        ),
        migrations.AlterUniqueTogether(
            name='dietaanimalfechainicio',
            unique_together={('FecIniCod', 'DieCod', 'AniCod')},
        ),
        migrations.AlterUniqueTogether(
            name='granja',
            unique_together={('GraCod', 'EmpCod')},
        ),
        migrations.AlterUniqueTogether(
            name='nutrientealimento',
            unique_together={('AliCod', 'NutCod')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('AlmCod', 'GraCod', 'EmpCod', 'AliCod')},
        ),
    ]
