# Generated by Django 5.0.6 on 2024-07-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_ciudad_unique_ciudad_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentotipo',
            name='AliTipCod',
            field=models.IntegerField(db_column='AliTipCod', max_length=2, primary_key=True, serialize=False),
        ),
    ]
