# Generated by Django 5.0.6 on 2024-07-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_alter_alimentotipo_alitipcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentotipo',
            name='AliTipCod',
            field=models.CharField(db_column='AliTipCod', max_length=2, primary_key=True, serialize=False),
        ),
    ]
