# Generated by Django 5.0.6 on 2024-07-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_alter_alimentotipo_alitipcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='PaiCod',
            field=models.ForeignKey(db_column='PaiCod', on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.pais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='PaiCod',
            field=models.ForeignKey(db_column='PaiCod', on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresa_paicod_set', to='Administrador.pais'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='PaiCod',
            field=models.ForeignKey(blank=True, db_column='PaiCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='granja_paicod_set', to='Administrador.pais'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='PaiCod',
            field=models.ForeignKey(blank=True, db_column='PaiCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores_paicod_set', to='Administrador.pais'),
        ),
    ]
