# Generated by Django 5.0.6 on 2024-07-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_alter_ciudad_paicod_alter_empresa_paicod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='DetPetCod',
        ),
    ]
