# Generated by Django 5.0.6 on 2024-07-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0008_remove_empresa_detpetcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='EmpCod',
            field=models.ForeignKey(db_column='EmpCod', on_delete=django.db.models.deletion.DO_NOTHING, related_name='almacen_empcod_set', to='Administrador.empresa', unique=True),
        ),
    ]
