# Generated by Django 5.0.6 on 2024-07-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0009_alter_almacen_empcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecerapedido',
            name='EmpCod',
            field=models.ForeignKey(db_column='EmpCod', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cabecerapedido_empcod_set', to='Administrador.empresa'),
        ),
        migrations.AlterField(
            model_name='cabecerapedido',
            name='GraCod',
            field=models.ForeignKey(db_column='GraCod', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cabecerapedido_gracod_set', to='Administrador.granja'),
        ),
    ]
